### ISSUE TITLE
General FYI on Testing NumPy Arrays

### ISSUE THREAD

**Issue by jy1909** [UBC-MDS/text_processing_util_mds24#34]
Check out these two functions on asserting NumPy arrays:

- `numpy.testing.assert_array_equal`: https://numpy.org/doc/stable/reference/generated/numpy.testing.assert_array_equal.html
- `numpy.testing.assert_array_almost_equal`: https://numpy.org/doc/stable/reference/generated/numpy.testing.assert_array_almost_equal.html

**Comment by MoNorouzi23** [comment]
I used them and already added to my function's tests. Thanks!
