### ISSUE TITLE
Frequency Function and Tests Edited

### ISSUE THREAD

**Issue by nassimgha** [UBC-MDS/text_processing_util_mds24#37]
Dear all,

Please check the changes I made to the function and the tests, as discussed.

Please let me know if I need to do anything else.

Thanks!

Nasim

**Comment by MoNorouzi23** [comment]
thanks, it was great

**Comment by jy1909** [comment]
Great! I think that's all four functions merged. I will do an overall review tomorrow and assuming nothing unexpected happens, that should be our last PR before submission.

**Comment by nassimgha** [comment]
Thanks everyone!
