### ISSUE TITLE
On the Progress of this Milestone

### ISSUE THREAD

**Issue by jy1909** [UBC-MDS/text_processing_util_mds24#53]
Since there are not too many edits to be done to the `example.ipynb` notebook, is it possible for everyone to finish their work on this file by end of day today or tomorrow noon?

We still need to read over all the documentations and `README.md` before linking this repo to Read the Docs for this milestone.

**Comment by MoNorouzi23** [comment]
Hey, I finalized the description and also the example of tf-idf function and pushed it.

**Comment by MoNorouzi23** [comment]
Do we have meeting on Thursday?

**Comment by nassimgha** [comment]
Hi, I finished the frequency vectorizer description and example. Please let me know what to do next.

**Comment by jy1909** [comment]
@MoNorouzi23 Yes, I think we should have a meeting on Thursday, as usual. There are a few things I think we need to address in terms of next steps.

**Comment by jy1909** [comment]
@nassimgha Thank you! I just left a small suggestion on your PR.

**Comment by jy1909** [comment]
Great! Now we have everyone's work on the vignette merged. There will be a few more things we will discuss about in tomorrow's meeting, but this is good so far.
