### ISSUE TITLE
On Revisions and Publishing to Read the Docs

### ISSUE THREAD

**Issue by jy1909** [UBC-MDS/text_processing_util_mds24#63]
@MoNorouzi23 @nassimgha @allan8392 

I have reviewed the documentation and the README.md and created the PR for the changes. Please review and merge. I also connected Read the Docs with our repository this morning.

After the PR is merged, please review everything again especially for proper writing. Note that please also review our Read the Docs pages to see if there anything that need to be changed. Link to Read the Docs: https://text-processing-util-mds24.readthedocs.io/en/latest/.

If there is no PR or concern raised by 10am on Saturday. I will submit.

**Comment by MoNorouzi23** [comment]
Thanks Jerry, I reviewed it on the website and it is well-formed.
