### ISSUE TITLE
Commit Messages and Semantic Release

### ISSUE THREAD

**Issue by jy1909** [UBC-MDS/text_processing_util_mds24#73]
@MoNorouzi23 @nassimgha @allan8392 

Friendly reminder to write the commit messages that work with semantic release.

For fixes, your commit message should start with `fix:`; e.g. `fix: Feedback addressed by fixing this bug`.

For features, your commit message should start with `feat:`, e.g. `feat: Feedback addressed by implement this feature`.

For more information, read this section of the notes: https://pages.github.ubc.ca/MDS-2023-24/DSCI_524_collab-sw-dev_book/materials/lectures/07_lecture-cd-semver-and-docs.html#conventional-commit-messages

**Comment by MoNorouzi23** [comment]
Hey Jerry, thanks for reminding!

**Comment by nassimgha** [comment]
Hi Jerry, Thanks for reminding us about this.
